### ISSUE TITLE
 Consider adding braille display gestures to assist with navigation using Braille input Feature

### ISSUE THREAD

**Issue by Kanwar5** [nvdaes/pcKbBrl#4]
I understand these settings are  configurable from the NVDA gestures dialogue, but I wonder if they could be added into the add-on itself for users who are less tech savvy.
 I was thinking about  the current functionality  of  a Braille keyboard and the universal commands which are used to navigate by sentence word or character, and implementing these into NVDA.

Pressing space with dots 1 or 4.4 to navigate by sentence/element, mimicking the NVDA up and down arrow keys respectively.
 Pressing space with dots 2 or 5 to navigate by word, mimicking NVDA control plus left and right arrows respectively, and pressing  Space with dots two and five together would read the current word.
Pressing space withdots 3 or 6 to navigate by character, mimicking the left and right arrow keys in NVDA.
 Pressing space with dots 1 2 and three  together, or 4 5 6 would move to the top or bottom of a window, document, webpage  or list  respectively. 
 Adding these gestures could remove the need for a Braille keyboard entirely, and instead Braille users could simply rely on a Braille line or simple display.  ## Is your feature request related to a problem? Please describe. ##

## Additional context ##
Add any other context about the feature request here.

**Comment by nvdaes** [comment]
Will look at this, maybe today or the next weekend. Thanks.

**Comment by nvdaes** [comment]
Hi, @Kanwar5 , thanks for this suggestion.
This is fixed in 2020.2-dev version. Also, this new version adds the possibility of speaking single dots when using one hand mode, requested in spanish community.
We can listen the current line with dots 1+4+space, but not the current word or character, since these two last commands are not assigned in braille displays like Focus 40 Blue 5 generation, used by me, and this command is not present in globalCommands.GlobalCommands to be assigned. this maybe done, but using different code, so it isn't included in this version.
I haven't assigned commands to use the gui like space+n to open NVDA's menu, since for this tasks it would be better to toggle off the add-on feature.
Please feel free to comment or reopen this issue if needed.
You can test this version:

https://github.com/nvdaes/pcKbBrl/releases/download/2020.2-dev/pcKbBrl-2020.2-dev.nvda-addon

**Comment by Kanwar5** [comment]
Thank you for your hard work in adding these gestures into the addon, to make it behave a bit more like a braille display.



Khalid Anwar
Please call 07497613820 or email AnwarKhalid850@gmail.com
